"$schema" = 'https://starship.rs/config-schema.json'

format = """

"""
palette = "rose-pine-dawn"

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay)"
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

