"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\n$directory\n$git_branch\n$git_status\n$fill\n$c\n$elixir\n$elm\n$golang\n$haskell\n$java\n$julia\n$nodejs\n$nim\n$rust\n$scala\n$python\n$time\n\n\n[󱞪](fg:iris) \\n
"""
palette = "rose-pine-dawn"

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay)"
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
style = "bg:overlay fg:love"
format = '[](fg:overlay)[$all_status$ahead_behind]($style)[](fg:overlay)'

[fill]
style = "fg:overlay"
symbol = " "


[java]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[󰎙 $version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[julia]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nim]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[󰆥 $version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[rust]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $version]($style)[](fg:overlay) "
disabled = false
symbol = " "


[time]
disabled = false
format = "[](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

